DROP TABLE IF EXISTS Compõem CASCADE;
DROP TABLE IF EXISTS Utiliza CASCADE;
DROP TABLE IF EXISTS ContatoPessoa CASCADE;
DROP TABLE IF EXISTS Exercício CASCADE;
DROP TABLE IF EXISTS Equipamento CASCADE;
DROP TABLE IF EXISTS PlanoTreino CASCADE;
DROP TABLE IF EXISTS Professor CASCADE;
DROP TABLE IF EXISTS Aluno CASCADE;
DROP TABLE IF EXISTS Pessoa CASCADE;


CREATE TABLE Pessoa (
    CPF CHAR(11) PRIMARY KEY,
    Nome VARCHAR(100) NOT NULL,
    Data_nasc DATE NOT NULL,
    Rua VARCHAR(100),
    Numero INT,
    Bairro VARCHAR(50),
    CEP CHAR(8)
);


CREATE TABLE Aluno (
    CPF CHAR(11) PRIMARY KEY REFERENCES Pessoa(CPF) ON DELETE CASCADE,
    Peso NUMERIC(5,2) NOT NULL,
    Altura NUMERIC(4,2) NOT NULL
);

CREATE TABLE Professor (
    CPF CHAR(11) PRIMARY KEY REFERENCES Pessoa(CPF) ON DELETE CASCADE,
    CREF VARCHAR(20) UNIQUE NOT NULL,
    Salario NUMERIC(10,2) NOT NULL
);

CREATE TABLE PlanoTreino (
    ID_treino SERIAL PRIMARY KEY,
    CPF_aluno CHAR(11) UNIQUE NOT NULL REFERENCES Aluno(CPF) ON DELETE CASCADE,
    Semanas INT NOT NULL,
    Data_início DATE NOT NULL
);

CREATE TABLE Equipamento (
    ID_equipamento SERIAL PRIMARY KEY,
    Nome VARCHAR(50) NOT NULL,
    Marca VARCHAR(50),
    Quantidade INT NOT NULL,
    Data_aquis DATE
);

CREATE TABLE Exercício (
    ID_exercício SERIAL PRIMARY KEY,
    Nome VARCHAR(50) NOT NULL,
    Descrição TEXT
);

CREATE TABLE ContatoPessoa (
    ID_contato SERIAL PRIMARY KEY,
    CPF_pessoa CHAR(11) NOT NULL REFERENCES Pessoa(CPF) ON DELETE CASCADE,
    Tipo VARCHAR(20) NOT NULL,
    Valor VARCHAR(100) NOT NULL
);

CREATE TABLE Utiliza (
    CPF_aluno CHAR(11) NOT NULL REFERENCES Aluno(CPF) ON DELETE CASCADE,
    ID_equipamento INT NOT NULL REFERENCES Equipamento(ID_equipamento) ON DELETE CASCADE,
    PRIMARY KEY (CPF_aluno, ID_equipamento)
);

CREATE TABLE Compõem (
    ID_treino INT NOT NULL REFERENCES PlanoTreino(ID_treino) ON DELETE CASCADE,
    ID_exercício INT NOT NULL REFERENCES Exercício(ID_exercício) ON DELETE CASCADE,
    PRIMARY KEY (ID_treino, ID_exercício)
);


ALTER TABLE Professor
ADD COLUMN Data_admissao DATE DEFAULT CURRENT_DATE;

ALTER TABLE Aluno
ADD UNIQUE (Peso);


